import { Page, Text, View, Document, StyleSheet, Font, Image } from '@react-pdf/renderer';
export default function DownloadFile({ note }) {
    const styles = StyleSheet.create({
        page: {
            fontFamily: 'Helvetica',
            fontSize: 11,
            paddingTop: 30,
            paddingLeft: 40,
            paddingRight: 40,
            paddingBottom: 30,
            lineHeight: 1.5,
        },
        headerContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            marginBottom: 20,
        },
        logoContainer: {
            backgroundColor: '#3730a3',
            width: 28,
            height: 28,
            borderRadius: 6,
            justifyContent: 'center',
            alignItems: 'center',
            marginRight: 8,
        },
        logoText: {
            color: 'white',
            fontSize: 16,
            fontWeight: 'bold',
        },
        headerText: {
            fontSize: 18,
            color: '#3730a3',
            fontWeight: 'bold',
        },
        title: {
            fontSize: 24,
            textAlign: 'center',
            marginBottom: 20,
            color: '#3730a3', 
            fontWeight: 'bold',
        },
        description: {
            textAlign: 'justify',
            marginBottom: 20,
        },
        image: {
            marginVertical: 15,
            marginHorizontal: 'auto',
            maxWidth: '80%',
        },
        footer: {
            position: 'absolute',
            fontSize: 10,
            bottom: 15,
            left: 40,
            right: 40,
            textAlign: 'center',
            color: 'grey',
        }
    });

    const fullImageUrl = note.imageUrl ? `http://localhost:4000${note.imageUrl}` : null;

    return (
        <Document title={note.title}>
            <Page size="A4" style={styles.page}>
                <View style={styles.headerContainer} fixed>
                    <View style={styles.logoContainer}>
                        <Text style={styles.logoText}>N</Text>
                    </View>
                    <Text style={styles.headerText}>Notes.io</Text>
                </View>
                <Text style={styles.title}>{note.title}</Text> 
                <Text style={styles.description}>{note.description}</Text>
                {fullImageUrl && <Image style={styles.image} src={{ uri: fullImageUrl, method: 'GET', headers: { 'Cache-Control': 'no-cache' } }} />}
                <Text style={styles.footer} fixed>
                    Generated by Notes.io
                </Text>
            </Page>
        </Document>
    )
}